// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const findTitlesByIMDb = `-- name: FindTitlesByIMDb :many
SELECT id, slug, name, kind, tmdb_id, imdb_id, rt_url, created_at, updated_at, match_status, match_source, matched_name, matched_year, match_attempts, match_attempted_at, next_match_at, rt_attempts, next_rt_at, justwatch_id, wikidata_id, fp_name, fp_kind, fp_premiere_date, fp_country, fp_fetched_at FROM titles WHERE imdb_id = ? ORDER BY id
`

func (q *Queries) FindTitlesByIMDb(ctx context.Context, imdbID sql.NullString) ([]Title, error) {
	rows, err := q.db.QueryContext(ctx, findTitlesByIMDb, imdbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Title{}
	for rows.Next() {
		var i Title
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.TmdbID,
			&i.ImdbID,
			&i.RtUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchStatus,
			&i.MatchSource,
			&i.MatchedName,
			&i.MatchedYear,
			&i.MatchAttempts,
			&i.MatchAttemptedAt,
			&i.NextMatchAt,
			&i.RtAttempts,
			&i.NextRtAt,
			&i.JustwatchID,
			&i.WikidataID,
			&i.FpName,
			&i.FpKind,
			&i.FpPremiereDate,
			&i.FpCountry,
			&i.FpFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTmdbRefsByIMDb = `-- name: FindTmdbRefsByIMDb :many
SELECT tmdb_kind, tmdb_id FROM tmdb_titles WHERE imdb_id = ?
`

type FindTmdbRefsByIMDbRow struct {
	TmdbKind string `json:"tmdb_kind"`
	TmdbID   string `json:"tmdb_id"`
}

func (q *Queries) FindTmdbRefsByIMDb(ctx context.Context, imdbID sql.NullString) ([]FindTmdbRefsByIMDbRow, error) {
	rows, err := q.db.QueryContext(ctx, findTmdbRefsByIMDb, imdbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTmdbRefsByIMDbRow{}
	for rows.Next() {
		var i FindTmdbRefsByIMDbRow
		if err := rows.Scan(&i.TmdbKind, &i.TmdbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestNetflixCountryWeek = `-- name: LatestNetflixCountryWeek :one
SELECT CAST(COALESCE(MAX(week), '') AS TEXT) FROM netflix_top10_countries WHERE country = ?
`

func (q *Queries) LatestNetflixCountryWeek(ctx context.Context, country string) (string, error) {
	row := q.db.QueryRowContext(ctx, latestNetflixCountryWeek, country)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const latestNetflixGlobalWeek = `-- name: LatestNetflixGlobalWeek :one
SELECT CAST(COALESCE(MAX(week), '') AS TEXT) FROM netflix_top10_global
`

func (q *Queries) LatestNetflixGlobalWeek(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, latestNetflixGlobalWeek)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const listChartCatalog = `-- name: ListChartCatalog :many
SELECT country, streaming_provider, category,
       CAST(MIN(ranked_on) AS TEXT) AS first_date,
       CAST(MAX(ranked_on) AS TEXT) AS latest_date,
       COUNT(*) AS dates,
       CAST(MAX(scraped_at) AS TEXT) AS last_scraped_at
FROM chart_snapshots
GROUP BY country, streaming_provider, category
ORDER BY country, streaming_provider, category
`

type ListChartCatalogRow struct {
	Country           string `json:"country"`
	StreamingProvider string `json:"streaming_provider"`
	Category          string `json:"category"`
	FirstDate         string `json:"first_date"`
	LatestDate        string `json:"latest_date"`
	Dates             int64  `json:"dates"`
	LastScrapedAt     string `json:"last_scraped_at"`
}

// Every stored chart: date range, number of dates, last scrape.
func (q *Queries) ListChartCatalog(ctx context.Context) ([]ListChartCatalogRow, error) {
	rows, err := q.db.QueryContext(ctx, listChartCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChartCatalogRow{}
	for rows.Next() {
		var i ListChartCatalogRow
		if err := rows.Scan(
			&i.Country,
			&i.StreamingProvider,
			&i.Category,
			&i.FirstDate,
			&i.LatestDate,
			&i.Dates,
			&i.LastScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartChangesSince = `-- name: ListChartChangesSince :many
SELECT id, ranked_on, country, streaming_provider, category, entry_count, signature, source, run_id, first_scraped_at, scraped_at, changed_at FROM chart_snapshots
WHERE scraped_at > CAST(?1 AS TEXT)
ORDER BY scraped_at, id
LIMIT ?2
`

type ListChartChangesSinceParams struct {
	Since string `json:"since"`
	Limit int64  `json:"limit"`
}

// Charts stored or re-scraped after a timestamp ('YYYY-MM-DD HH:MM:SS' UTC).
func (q *Queries) ListChartChangesSince(ctx context.Context, arg ListChartChangesSinceParams) ([]ChartSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listChartChangesSince, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChartSnapshot{}
	for rows.Next() {
		var i ChartSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.RankedOn,
			&i.Country,
			&i.StreamingProvider,
			&i.Category,
			&i.EntryCount,
			&i.Signature,
			&i.Source,
			&i.RunID,
			&i.FirstScrapedAt,
			&i.ScrapedAt,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartDates = `-- name: ListChartDates :many
SELECT ranked_on, category, entry_count, scraped_at
FROM chart_snapshots
WHERE country = ?1
  AND streaming_provider = ?2
  AND (CAST(?3 AS TEXT) = '' OR category = ?3)
ORDER BY ranked_on DESC, category
LIMIT ?4
`

type ListChartDatesParams struct {
	Country  string `json:"country"`
	Provider string `json:"provider"`
	Category string `json:"category"`
	Limit    int64  `json:"limit"`
}

type ListChartDatesRow struct {
	RankedOn   string    `json:"ranked_on"`
	Category   string    `json:"category"`
	EntryCount int64     `json:"entry_count"`
	ScrapedAt  time.Time `json:"scraped_at"`
}

func (q *Queries) ListChartDates(ctx context.Context, arg ListChartDatesParams) ([]ListChartDatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChartDates,
		arg.Country,
		arg.Provider,
		arg.Category,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChartDatesRow{}
	for rows.Next() {
		var i ListChartDatesRow
		if err := rows.Scan(
			&i.RankedOn,
			&i.Category,
			&i.EntryCount,
			&i.ScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChartEntries = `-- name: ListChartEntries :many

SELECT CAST(r.ranked_on AS TEXT) AS ranked_on,
       CAST(r.country AS TEXT) AS country,
       r.streaming_provider,
       r.category,
       r.rank,
       r.season_number,
       t.id AS title_id,
       t.slug,
       t.name,
       t.kind,
       t.tmdb_id,
       t.imdb_id
FROM rankings r
JOIN titles t ON t.id = r.title_id
WHERE r.ranked_on >= CAST(?1 AS TEXT)
  AND r.ranked_on <= CAST(?2 AS TEXT)
  AND (CAST(?3 AS TEXT) = '' OR r.country = ?3)
  AND (CAST(?4 AS TEXT) = '' OR r.streaming_provider = ?4)
  AND (CAST(?5 AS TEXT) = '' OR r.category = ?5)
ORDER BY r.ranked_on, r.country, r.streaming_provider, r.category, r.rank
`

type ListChartEntriesParams struct {
	FromDate string `json:"from_date"`
	ToDate   string `json:"to_date"`
	Country  string `json:"country"`
	Provider string `json:"provider"`
	Category string `json:"category"`
}

type ListChartEntriesRow struct {
	RankedOn          string         `json:"ranked_on"`
	Country           string         `json:"country"`
	StreamingProvider string         `json:"streaming_provider"`
	Category          string         `json:"category"`
	Rank              int64          `json:"rank"`
	SeasonNumber      sql.NullInt64  `json:"season_number"`
	TitleID           int64          `json:"title_id"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	Kind              string         `json:"kind"`
	TmdbID            sql.NullString `json:"tmdb_id"`
	ImdbID            sql.NullString `json:"imdb_id"`
}

// Chart entries over a date range, for history, movers, leaderboards and
// analytics (computed in Go). Empty filters match all.
func (q *Queries) ListChartEntries(ctx context.Context, arg ListChartEntriesParams) ([]ListChartEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChartEntries,
		arg.FromDate,
		arg.ToDate,
		arg.Country,
		arg.Provider,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChartEntriesRow{}
	for rows.Next() {
		var i ListChartEntriesRow
		if err := rows.Scan(
			&i.RankedOn,
			&i.Country,
			&i.StreamingProvider,
			&i.Category,
			&i.Rank,
			&i.SeasonNumber,
			&i.TitleID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.TmdbID,
			&i.ImdbID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetflixCountriesByTmdb = `-- name: ListNetflixCountriesByTmdb :many
SELECT c.country, c.week, c.category, c.weekly_rank, c.netflix_title_id, c.show_title, c.season_title, c.cumulative_weeks
FROM netflix_top10_countries c
JOIN netflix_titles n ON n.id = c.netflix_title_id
WHERE n.kind = ?1 AND n.tmdb_id = ?2
ORDER BY c.week, c.country
`

type ListNetflixCountriesByTmdbParams struct {
	Kind   string         `json:"kind"`
	TmdbID sql.NullString `json:"tmdb_id"`
}

func (q *Queries) ListNetflixCountriesByTmdb(ctx context.Context, arg ListNetflixCountriesByTmdbParams) ([]NetflixTop10Country, error) {
	rows, err := q.db.QueryContext(ctx, listNetflixCountriesByTmdb, arg.Kind, arg.TmdbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetflixTop10Country{}
	for rows.Next() {
		var i NetflixTop10Country
		if err := rows.Scan(
			&i.Country,
			&i.Week,
			&i.Category,
			&i.WeeklyRank,
			&i.NetflixTitleID,
			&i.ShowTitle,
			&i.SeasonTitle,
			&i.CumulativeWeeks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetflixCountryWeek = `-- name: ListNetflixCountryWeek :many
SELECT c.country, c.week, c.category, c.weekly_rank, c.netflix_title_id, c.show_title, c.season_title, c.cumulative_weeks, n.tmdb_id, n.imdb_id, n.kind
FROM netflix_top10_countries c
JOIN netflix_titles n ON n.id = c.netflix_title_id
WHERE c.country = ?1 AND c.week = ?2
  AND (CAST(?3 AS TEXT) = '' OR c.category = ?3)
ORDER BY c.category, c.weekly_rank
`

type ListNetflixCountryWeekParams struct {
	Country  string `json:"country"`
	Week     string `json:"week"`
	Category string `json:"category"`
}

type ListNetflixCountryWeekRow struct {
	Country         string         `json:"country"`
	Week            string         `json:"week"`
	Category        string         `json:"category"`
	WeeklyRank      int64          `json:"weekly_rank"`
	NetflixTitleID  int64          `json:"netflix_title_id"`
	ShowTitle       string         `json:"show_title"`
	SeasonTitle     sql.NullString `json:"season_title"`
	CumulativeWeeks sql.NullInt64  `json:"cumulative_weeks"`
	TmdbID          sql.NullString `json:"tmdb_id"`
	ImdbID          sql.NullString `json:"imdb_id"`
	Kind            string         `json:"kind"`
}

func (q *Queries) ListNetflixCountryWeek(ctx context.Context, arg ListNetflixCountryWeekParams) ([]ListNetflixCountryWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetflixCountryWeek, arg.Country, arg.Week, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetflixCountryWeekRow{}
	for rows.Next() {
		var i ListNetflixCountryWeekRow
		if err := rows.Scan(
			&i.Country,
			&i.Week,
			&i.Category,
			&i.WeeklyRank,
			&i.NetflixTitleID,
			&i.ShowTitle,
			&i.SeasonTitle,
			&i.CumulativeWeeks,
			&i.TmdbID,
			&i.ImdbID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetflixGlobalByTmdb = `-- name: ListNetflixGlobalByTmdb :many
SELECT g.week, g.category, g.weekly_rank, g.netflix_title_id, g.show_title, g.season_title, g.weekly_hours_viewed, g.runtime_hours, g.weekly_views, g.cumulative_weeks
FROM netflix_top10_global g
JOIN netflix_titles n ON n.id = g.netflix_title_id
WHERE n.kind = ?1 AND n.tmdb_id = ?2
ORDER BY g.week, g.category
`

type ListNetflixGlobalByTmdbParams struct {
	Kind   string         `json:"kind"`
	TmdbID sql.NullString `json:"tmdb_id"`
}

func (q *Queries) ListNetflixGlobalByTmdb(ctx context.Context, arg ListNetflixGlobalByTmdbParams) ([]NetflixTop10Global, error) {
	rows, err := q.db.QueryContext(ctx, listNetflixGlobalByTmdb, arg.Kind, arg.TmdbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetflixTop10Global{}
	for rows.Next() {
		var i NetflixTop10Global
		if err := rows.Scan(
			&i.Week,
			&i.Category,
			&i.WeeklyRank,
			&i.NetflixTitleID,
			&i.ShowTitle,
			&i.SeasonTitle,
			&i.WeeklyHoursViewed,
			&i.RuntimeHours,
			&i.WeeklyViews,
			&i.CumulativeWeeks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetflixGlobalRange = `-- name: ListNetflixGlobalRange :many
SELECT g.week, g.category, g.weekly_rank, g.show_title, g.weekly_hours_viewed, g.weekly_views, n.tmdb_id, n.kind
FROM netflix_top10_global g
JOIN netflix_titles n ON n.id = g.netflix_title_id
WHERE g.week >= CAST(?1 AS TEXT) AND g.week <= CAST(?2 AS TEXT)
ORDER BY g.week, g.category, g.weekly_rank
`

type ListNetflixGlobalRangeParams struct {
	FromWeek string `json:"from_week"`
	ToWeek   string `json:"to_week"`
}

type ListNetflixGlobalRangeRow struct {
	Week              string         `json:"week"`
	Category          string         `json:"category"`
	WeeklyRank        int64          `json:"weekly_rank"`
	ShowTitle         string         `json:"show_title"`
	WeeklyHoursViewed sql.NullInt64  `json:"weekly_hours_viewed"`
	WeeklyViews       sql.NullInt64  `json:"weekly_views"`
	TmdbID            sql.NullString `json:"tmdb_id"`
	Kind              string         `json:"kind"`
}

// Global weekly rows with TMDB IDs in a week range, for calibration.
func (q *Queries) ListNetflixGlobalRange(ctx context.Context, arg ListNetflixGlobalRangeParams) ([]ListNetflixGlobalRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetflixGlobalRange, arg.FromWeek, arg.ToWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetflixGlobalRangeRow{}
	for rows.Next() {
		var i ListNetflixGlobalRangeRow
		if err := rows.Scan(
			&i.Week,
			&i.Category,
			&i.WeeklyRank,
			&i.ShowTitle,
			&i.WeeklyHoursViewed,
			&i.WeeklyViews,
			&i.TmdbID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetflixGlobalWeek = `-- name: ListNetflixGlobalWeek :many
SELECT g.week, g.category, g.weekly_rank, g.netflix_title_id, g.show_title, g.season_title, g.weekly_hours_viewed, g.runtime_hours, g.weekly_views, g.cumulative_weeks, n.tmdb_id, n.imdb_id, n.kind
FROM netflix_top10_global g
JOIN netflix_titles n ON n.id = g.netflix_title_id
WHERE g.week = ?1
  AND (CAST(?2 AS TEXT) = '' OR g.category = ?2)
ORDER BY g.category, g.weekly_rank
`

type ListNetflixGlobalWeekParams struct {
	Week     string `json:"week"`
	Category string `json:"category"`
}

type ListNetflixGlobalWeekRow struct {
	Week              string          `json:"week"`
	Category          string          `json:"category"`
	WeeklyRank        int64           `json:"weekly_rank"`
	NetflixTitleID    int64           `json:"netflix_title_id"`
	ShowTitle         string          `json:"show_title"`
	SeasonTitle       sql.NullString  `json:"season_title"`
	WeeklyHoursViewed sql.NullInt64   `json:"weekly_hours_viewed"`
	RuntimeHours      sql.NullFloat64 `json:"runtime_hours"`
	WeeklyViews       sql.NullInt64   `json:"weekly_views"`
	CumulativeWeeks   sql.NullInt64   `json:"cumulative_weeks"`
	TmdbID            sql.NullString  `json:"tmdb_id"`
	ImdbID            sql.NullString  `json:"imdb_id"`
	Kind              string          `json:"kind"`
}

func (q *Queries) ListNetflixGlobalWeek(ctx context.Context, arg ListNetflixGlobalWeekParams) ([]ListNetflixGlobalWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetflixGlobalWeek, arg.Week, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetflixGlobalWeekRow{}
	for rows.Next() {
		var i ListNetflixGlobalWeekRow
		if err := rows.Scan(
			&i.Week,
			&i.Category,
			&i.WeeklyRank,
			&i.NetflixTitleID,
			&i.ShowTitle,
			&i.SeasonTitle,
			&i.WeeklyHoursViewed,
			&i.RuntimeHours,
			&i.WeeklyViews,
			&i.CumulativeWeeks,
			&i.TmdbID,
			&i.ImdbID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetflixMostPopular = `-- name: ListNetflixMostPopular :many
SELECT p.category, p.rank, p.netflix_title_id, p.show_title, p.season_title, p.hours_viewed_91d, p.runtime_hours, p.views_91d, n.tmdb_id, n.imdb_id, n.kind
FROM netflix_most_popular p
JOIN netflix_titles n ON n.id = p.netflix_title_id
WHERE (CAST(?1 AS TEXT) = '' OR p.category = ?1)
ORDER BY p.category, p.rank
`

type ListNetflixMostPopularRow struct {
	Category       string          `json:"category"`
	Rank           int64           `json:"rank"`
	NetflixTitleID int64           `json:"netflix_title_id"`
	ShowTitle      string          `json:"show_title"`
	SeasonTitle    sql.NullString  `json:"season_title"`
	HoursViewed91d sql.NullInt64   `json:"hours_viewed_91d"`
	RuntimeHours   sql.NullFloat64 `json:"runtime_hours"`
	Views91d       sql.NullInt64   `json:"views_91d"`
	TmdbID         sql.NullString  `json:"tmdb_id"`
	ImdbID         sql.NullString  `json:"imdb_id"`
	Kind           string          `json:"kind"`
}

func (q *Queries) ListNetflixMostPopular(ctx context.Context, category string) ([]ListNetflixMostPopularRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetflixMostPopular, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetflixMostPopularRow{}
	for rows.Next() {
		var i ListNetflixMostPopularRow
		if err := rows.Scan(
			&i.Category,
			&i.Rank,
			&i.NetflixTitleID,
			&i.ShowTitle,
			&i.SeasonTitle,
			&i.HoursViewed91d,
			&i.RuntimeHours,
			&i.Views91d,
			&i.TmdbID,
			&i.ImdbID,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTitlesByTmdbRef = `-- name: ListTitlesByTmdbRef :many
SELECT id, slug, name, kind, tmdb_id, imdb_id, rt_url, created_at, updated_at, match_status, match_source, matched_name, matched_year, match_attempts, match_attempted_at, next_match_at, rt_attempts, next_rt_at, justwatch_id, wikidata_id, fp_name, fp_kind, fp_premiere_date, fp_country, fp_fetched_at FROM titles
WHERE kind = ?1 AND tmdb_id = ?2
ORDER BY id
`

type ListTitlesByTmdbRefParams struct {
	Kind   string         `json:"kind"`
	TmdbID sql.NullString `json:"tmdb_id"`
}

func (q *Queries) ListTitlesByTmdbRef(ctx context.Context, arg ListTitlesByTmdbRefParams) ([]Title, error) {
	rows, err := q.db.QueryContext(ctx, listTitlesByTmdbRef, arg.Kind, arg.TmdbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Title{}
	for rows.Next() {
		var i Title
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.TmdbID,
			&i.ImdbID,
			&i.RtUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchStatus,
			&i.MatchSource,
			&i.MatchedName,
			&i.MatchedYear,
			&i.MatchAttempts,
			&i.MatchAttemptedAt,
			&i.NextMatchAt,
			&i.RtAttempts,
			&i.NextRtAt,
			&i.JustwatchID,
			&i.WikidataID,
			&i.FpName,
			&i.FpKind,
			&i.FpPremiereDate,
			&i.FpCountry,
			&i.FpFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
