// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (name, key_prefix, key_hash)
VALUES (?, ?, ?)
RETURNING id, name, key_prefix, key_hash, created_at, rotated_at, last_used_at
`

type CreateAPIKeyParams struct {
	Name      string `json:"name"`
	KeyPrefix string `json:"key_prefix"`
	KeyHash   string `json:"key_hash"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey, arg.Name, arg.KeyPrefix, arg.KeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAPIKeys = `-- name: ListAPIKeys :many

SELECT id, name, key_prefix, key_hash, created_at, rotated_at, last_used_at
FROM api_keys
ORDER BY id
`

// API keys for the public API, and admin-editable settings.
func (q *Queries) ListAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppSettings = `-- name: ListAppSettings :many
SELECT key, value, updated_at FROM app_settings
`

func (q *Queries) ListAppSettings(ctx context.Context) ([]AppSetting, error) {
	rows, err := q.db.QueryContext(ctx, listAppSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSetting{}
	for rows.Next() {
		var i AppSetting
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameAPIKey = `-- name: RenameAPIKey :one
UPDATE api_keys
SET name = ?
WHERE id = ?
RETURNING id, name, key_prefix, key_hash, created_at, rotated_at, last_used_at
`

type RenameAPIKeyParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameAPIKey(ctx context.Context, arg RenameAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, renameAPIKey, arg.Name, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const rotateAPIKey = `-- name: RotateAPIKey :one
UPDATE api_keys
SET key_prefix = ?, key_hash = ?, rotated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, key_prefix, key_hash, created_at, rotated_at, last_used_at
`

type RotateAPIKeyParams struct {
	KeyPrefix string `json:"key_prefix"`
	KeyHash   string `json:"key_hash"`
	ID        int64  `json:"id"`
}

func (q *Queries) RotateAPIKey(ctx context.Context, arg RotateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, rotateAPIKey, arg.KeyPrefix, arg.KeyHash, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchAPIKey, id)
	return err
}

const upsertAppSetting = `-- name: UpsertAppSetting :exec
INSERT INTO app_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type UpsertAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertAppSetting(ctx context.Context, arg UpsertAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppSetting, arg.Key, arg.Value)
	return err
}
