// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: flixpatrol.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getTitleBySlug = `-- name: GetTitleBySlug :one
SELECT id, slug, name, kind, tmdb_id, imdb_id, rt_url, created_at, updated_at
FROM titles
WHERE slug = ?
`

func (q *Queries) GetTitleBySlug(ctx context.Context, slug string) (Title, error) {
	row := q.db.QueryRowContext(ctx, getTitleBySlug, slug)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.TmdbID,
		&i.ImdbID,
		&i.RtUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTitleByID = `-- name: GetTitleByID :one
SELECT id, slug, name, kind, tmdb_id, imdb_id, rt_url, created_at, updated_at
FROM titles
WHERE id = ?
`

func (q *Queries) GetTitleByID(ctx context.Context, id int64) (Title, error) {
	row := q.db.QueryRowContext(ctx, getTitleByID, id)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.TmdbID,
		&i.ImdbID,
		&i.RtUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTitles = `-- name: ListTitles :many
SELECT id, slug, name, kind, tmdb_id, imdb_id, rt_url, created_at, updated_at
FROM titles
WHERE (? = '' OR kind = ?)
  AND (? = '' OR name LIKE '%' || ? || '%')
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type ListTitlesParams struct {
	Kind   string `json:"kind"`
	Name   string `json:"name"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListTitles(ctx context.Context, arg ListTitlesParams) ([]Title, error) {
	rows, err := q.db.QueryContext(ctx, listTitles,
		arg.Kind, arg.Kind,
		arg.Name, arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Title
	for rows.Next() {
		var i Title
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.TmdbID,
			&i.ImdbID,
			&i.RtUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const countTitles = `-- name: CountTitles :one
SELECT COUNT(*)
FROM titles
WHERE (? = '' OR kind = ?)
  AND (? = '' OR name LIKE '%' || ? || '%')
`

type CountTitlesParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

func (q *Queries) CountTitles(ctx context.Context, arg CountTitlesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTitles,
		arg.Kind, arg.Kind,
		arg.Name, arg.Name,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateTitleIDs = `-- name: UpdateTitleIDs :one
UPDATE titles
SET
    tmdb_id    = ?,
    imdb_id    = ?,
    rt_url     = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, slug, name, kind, tmdb_id, imdb_id, rt_url, created_at, updated_at
`

type UpdateTitleIDsParams struct {
	TmdbID sql.NullString `json:"tmdb_id"`
	ImdbID sql.NullString `json:"imdb_id"`
	RtUrl  sql.NullString `json:"rt_url"`
	ID     int64          `json:"id"`
}

func (q *Queries) UpdateTitleIDs(ctx context.Context, arg UpdateTitleIDsParams) (Title, error) {
	row := q.db.QueryRowContext(ctx, updateTitleIDs,
		arg.TmdbID,
		arg.ImdbID,
		arg.RtUrl,
		arg.ID,
	)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.TmdbID,
		&i.ImdbID,
		&i.RtUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRanking = `-- name: UpsertRanking :one
INSERT INTO rankings (title_id, ranked_on, country, streaming_provider, category, rank, season_number)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ranked_on, country, streaming_provider, category, rank) DO UPDATE SET
    title_id      = excluded.title_id,
    season_number = excluded.season_number,
    scraped_at    = CURRENT_TIMESTAMP
RETURNING id, title_id, ranked_on, country, streaming_provider, category, rank, season_number, scraped_at
`

type UpsertRankingParams struct {
	TitleID           int64         `json:"title_id"`
	RankedOn          time.Time     `json:"ranked_on"`
	Country           interface{}   `json:"country"`
	StreamingProvider string        `json:"streaming_provider"`
	Category          string        `json:"category"`
	Rank              int64         `json:"rank"`
	SeasonNumber      sql.NullInt64 `json:"season_number"`
}

func (q *Queries) UpsertRanking(ctx context.Context, arg UpsertRankingParams) (Ranking, error) {
	row := q.db.QueryRowContext(ctx, upsertRanking,
		arg.TitleID,
		arg.RankedOn,
		arg.Country,
		arg.StreamingProvider,
		arg.Category,
		arg.Rank,
		arg.SeasonNumber,
	)
	var i Ranking
	err := row.Scan(
		&i.ID,
		&i.TitleID,
		&i.RankedOn,
		&i.Country,
		&i.StreamingProvider,
		&i.Category,
		&i.Rank,
		&i.SeasonNumber,
		&i.ScrapedAt,
	)
	return i, err
}

const upsertTitle = `-- name: UpsertTitle :one

INSERT INTO titles (slug, name, kind, tmdb_id, imdb_id, rt_url)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(slug) DO UPDATE SET
    name       = excluded.name,
    kind       = excluded.kind,
    tmdb_id    = COALESCE(excluded.tmdb_id, titles.tmdb_id),
    imdb_id    = COALESCE(excluded.imdb_id, titles.imdb_id),
    rt_url     = COALESCE(excluded.rt_url, titles.rt_url),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, slug, name, kind, tmdb_id, imdb_id, rt_url, created_at, updated_at
`

type UpsertTitleParams struct {
	Slug   string         `json:"slug"`
	Name   string         `json:"name"`
	Kind   string         `json:"kind"`
	TmdbID sql.NullString `json:"tmdb_id"`
	ImdbID sql.NullString `json:"imdb_id"`
	RtUrl  sql.NullString `json:"rt_url"`
}

// Titles (movies + tv shows) + daily rankings (Top 10).
func (q *Queries) UpsertTitle(ctx context.Context, arg UpsertTitleParams) (Title, error) {
	row := q.db.QueryRowContext(ctx, upsertTitle,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.TmdbID,
		arg.ImdbID,
		arg.RtUrl,
	)
	var i Title
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.TmdbID,
		&i.ImdbID,
		&i.RtUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
