// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const countIMDbRatings = `-- name: CountIMDbRatings :one
SELECT COUNT(*) FROM imdb_ratings
`

func (q *Queries) CountIMDbRatings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIMDbRatings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNetflixTitlesByMatchStatus = `-- name: CountNetflixTitlesByMatchStatus :many
SELECT match_status, COUNT(*) AS titles FROM netflix_titles GROUP BY match_status
`

type CountNetflixTitlesByMatchStatusRow struct {
	MatchStatus string `json:"match_status"`
	Titles      int64  `json:"titles"`
}

func (q *Queries) CountNetflixTitlesByMatchStatus(ctx context.Context) ([]CountNetflixTitlesByMatchStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countNetflixTitlesByMatchStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNetflixTitlesByMatchStatusRow{}
	for rows.Next() {
		var i CountNetflixTitlesByMatchStatusRow
		if err := rows.Scan(&i.MatchStatus, &i.Titles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNetflixMostPopular = `-- name: DeleteNetflixMostPopular :exec
DELETE FROM netflix_most_popular
`

func (q *Queries) DeleteNetflixMostPopular(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteNetflixMostPopular)
	return err
}

const ensureNetflixTitle = `-- name: EnsureNetflixTitle :one
INSERT INTO netflix_titles (show_title, kind) VALUES (?, ?)
ON CONFLICT(show_title, kind) DO UPDATE SET show_title = excluded.show_title
RETURNING id, show_title, kind, tmdb_id, imdb_id, title_id, match_status, match_source, match_attempts, next_match_at, created_at, updated_at
`

type EnsureNetflixTitleParams struct {
	ShowTitle string `json:"show_title"`
	Kind      string `json:"kind"`
}

func (q *Queries) EnsureNetflixTitle(ctx context.Context, arg EnsureNetflixTitleParams) (NetflixTitle, error) {
	row := q.db.QueryRowContext(ctx, ensureNetflixTitle, arg.ShowTitle, arg.Kind)
	var i NetflixTitle
	err := row.Scan(
		&i.ID,
		&i.ShowTitle,
		&i.Kind,
		&i.TmdbID,
		&i.ImdbID,
		&i.TitleID,
		&i.MatchStatus,
		&i.MatchSource,
		&i.MatchAttempts,
		&i.NextMatchAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFlixPatrolTitlesByName = `-- name: FindFlixPatrolTitlesByName :many
SELECT DISTINCT t.id, t.slug, t.name, t.kind, t.tmdb_id, t.imdb_id, t.rt_url, t.created_at, t.updated_at, t.match_status, t.match_source, t.matched_name, t.matched_year, t.match_attempts, t.match_attempted_at, t.next_match_at, t.rt_attempts, t.next_rt_at, t.justwatch_id, t.wikidata_id, t.fp_name, t.fp_kind, t.fp_premiere_date, t.fp_country, t.fp_fetched_at
FROM titles t
JOIN rankings r ON r.title_id = t.id AND r.streaming_provider = 'netflix'
WHERE t.kind = ?1
  AND COALESCE(t.tmdb_id, '') <> ''
  AND (lower(t.name) = lower(?2) OR lower(COALESCE(t.fp_name, '')) = lower(?2))
`

type FindFlixPatrolTitlesByNameParams struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}

// FlixPatrol titles of a kind with this exact name (case-insensitive) that
// charted on Netflix, to match Netflix titles without another lookup.
func (q *Queries) FindFlixPatrolTitlesByName(ctx context.Context, arg FindFlixPatrolTitlesByNameParams) ([]Title, error) {
	rows, err := q.db.QueryContext(ctx, findFlixPatrolTitlesByName, arg.Kind, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Title{}
	for rows.Next() {
		var i Title
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.TmdbID,
			&i.ImdbID,
			&i.RtUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MatchStatus,
			&i.MatchSource,
			&i.MatchedName,
			&i.MatchedYear,
			&i.MatchAttempts,
			&i.MatchAttemptedAt,
			&i.NextMatchAt,
			&i.RtAttempts,
			&i.NextRtAt,
			&i.JustwatchID,
			&i.WikidataID,
			&i.FpName,
			&i.FpKind,
			&i.FpPremiereDate,
			&i.FpCountry,
			&i.FpFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDataImport = `-- name: GetDataImport :one

SELECT source, etag, last_modified, "rows", imported_at FROM data_imports WHERE source = ?
`

// File imports: Netflix official Top 10 and IMDb ratings.
func (q *Queries) GetDataImport(ctx context.Context, source string) (DataImport, error) {
	row := q.db.QueryRowContext(ctx, getDataImport, source)
	var i DataImport
	err := row.Scan(
		&i.Source,
		&i.Etag,
		&i.LastModified,
		&i.Rows,
		&i.ImportedAt,
	)
	return i, err
}

const getIMDbRating = `-- name: GetIMDbRating :one
SELECT imdb_id, average_rating, num_votes, imported_at FROM imdb_ratings WHERE imdb_id = ?
`

func (q *Queries) GetIMDbRating(ctx context.Context, imdbID string) (ImdbRating, error) {
	row := q.db.QueryRowContext(ctx, getIMDbRating, imdbID)
	var i ImdbRating
	err := row.Scan(
		&i.ImdbID,
		&i.AverageRating,
		&i.NumVotes,
		&i.ImportedAt,
	)
	return i, err
}

const insertNetflixMostPopular = `-- name: InsertNetflixMostPopular :exec
INSERT INTO netflix_most_popular (category, rank, netflix_title_id, show_title, season_title, hours_viewed_91d, runtime_hours, views_91d)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNetflixMostPopularParams struct {
	Category       string          `json:"category"`
	Rank           int64           `json:"rank"`
	NetflixTitleID int64           `json:"netflix_title_id"`
	ShowTitle      string          `json:"show_title"`
	SeasonTitle    sql.NullString  `json:"season_title"`
	HoursViewed91d sql.NullInt64   `json:"hours_viewed_91d"`
	RuntimeHours   sql.NullFloat64 `json:"runtime_hours"`
	Views91d       sql.NullInt64   `json:"views_91d"`
}

func (q *Queries) InsertNetflixMostPopular(ctx context.Context, arg InsertNetflixMostPopularParams) error {
	_, err := q.db.ExecContext(ctx, insertNetflixMostPopular,
		arg.Category,
		arg.Rank,
		arg.NetflixTitleID,
		arg.ShowTitle,
		arg.SeasonTitle,
		arg.HoursViewed91d,
		arg.RuntimeHours,
		arg.Views91d,
	)
	return err
}

const listDataImports = `-- name: ListDataImports :many
SELECT source, etag, last_modified, "rows", imported_at FROM data_imports ORDER BY source
`

func (q *Queries) ListDataImports(ctx context.Context) ([]DataImport, error) {
	rows, err := q.db.QueryContext(ctx, listDataImports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DataImport{}
	for rows.Next() {
		var i DataImport
		if err := rows.Scan(
			&i.Source,
			&i.Etag,
			&i.LastModified,
			&i.Rows,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIMDbRatings = `-- name: ListIMDbRatings :many
SELECT imdb_id, average_rating, num_votes, imported_at FROM imdb_ratings WHERE imdb_id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListIMDbRatings(ctx context.Context, ids []string) ([]ImdbRating, error) {
	query := listIMDbRatings
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImdbRating{}
	for rows.Next() {
		var i ImdbRating
		if err := rows.Scan(
			&i.ImdbID,
			&i.AverageRating,
			&i.NumVotes,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnownIMDbIDs = `-- name: ListKnownIMDbIDs :many
SELECT imdb_id FROM titles WHERE COALESCE(imdb_id, '') <> ''
UNION SELECT imdb_id FROM tmdb_titles WHERE COALESCE(imdb_id, '') <> ''
UNION SELECT imdb_id FROM title_ratings WHERE COALESCE(imdb_id, '') <> ''
UNION SELECT imdb_id FROM netflix_titles WHERE COALESCE(imdb_id, '') <> ''
`

// Every IMDb ID metareel knows, for filtering the IMDb ratings dataset.
func (q *Queries) ListKnownIMDbIDs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listKnownIMDbIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var imdb_id sql.NullString
		if err := rows.Scan(&imdb_id); err != nil {
			return nil, err
		}
		items = append(items, imdb_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetflixTitlesDueForMatch = `-- name: ListNetflixTitlesDueForMatch :many
SELECT n.id, n.show_title, n.kind, n.tmdb_id, n.imdb_id, n.title_id, n.match_status, n.match_source, n.match_attempts, n.next_match_at, n.created_at, n.updated_at,
       CAST(COALESCE(
           (SELECT MIN(g.week) FROM netflix_top10_global g WHERE g.netflix_title_id = n.id),
           (SELECT MIN(c.week) FROM netflix_top10_countries c WHERE c.netflix_title_id = n.id),
           '') AS TEXT) AS first_week
FROM netflix_titles n
WHERE n.match_status IN ('pending', 'unmatched')
  AND (n.next_match_at IS NULL OR n.next_match_at <= CURRENT_TIMESTAMP)
ORDER BY CASE WHEN n.match_status = 'pending' THEN 0 ELSE 1 END,
         (SELECT MAX(g.week) FROM netflix_top10_global g WHERE g.netflix_title_id = n.id) DESC
LIMIT ?1
`

type ListNetflixTitlesDueForMatchRow struct {
	NetflixTitle NetflixTitle `json:"netflix_title"`
	FirstWeek    string       `json:"first_week"`
}

// first_week is the first week the title was in any imported list
// (YYYY-MM-DD, or ” if only in the most-popular list).
func (q *Queries) ListNetflixTitlesDueForMatch(ctx context.Context, limit int64) ([]ListNetflixTitlesDueForMatchRow, error) {
	rows, err := q.db.QueryContext(ctx, listNetflixTitlesDueForMatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNetflixTitlesDueForMatchRow{}
	for rows.Next() {
		var i ListNetflixTitlesDueForMatchRow
		if err := rows.Scan(
			&i.NetflixTitle.ID,
			&i.NetflixTitle.ShowTitle,
			&i.NetflixTitle.Kind,
			&i.NetflixTitle.TmdbID,
			&i.NetflixTitle.ImdbID,
			&i.NetflixTitle.TitleID,
			&i.NetflixTitle.MatchStatus,
			&i.NetflixTitle.MatchSource,
			&i.NetflixTitle.MatchAttempts,
			&i.NetflixTitle.NextMatchAt,
			&i.NetflixTitle.CreatedAt,
			&i.NetflixTitle.UpdatedAt,
			&i.FirstWeek,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDataImport = `-- name: SaveDataImport :exec
INSERT INTO data_imports (source, etag, last_modified, rows, imported_at)
VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(source) DO UPDATE SET
    etag = excluded.etag, last_modified = excluded.last_modified, rows = excluded.rows, imported_at = CURRENT_TIMESTAMP
`

type SaveDataImportParams struct {
	Source       string         `json:"source"`
	Etag         sql.NullString `json:"etag"`
	LastModified sql.NullString `json:"last_modified"`
	Rows         int64          `json:"rows"`
}

func (q *Queries) SaveDataImport(ctx context.Context, arg SaveDataImportParams) error {
	_, err := q.db.ExecContext(ctx, saveDataImport,
		arg.Source,
		arg.Etag,
		arg.LastModified,
		arg.Rows,
	)
	return err
}

const saveNetflixTitleMatch = `-- name: SaveNetflixTitleMatch :exec
UPDATE netflix_titles
SET tmdb_id        = COALESCE(?1, tmdb_id),
    imdb_id        = COALESCE(?2, imdb_id),
    title_id       = COALESCE(?3, title_id),
    match_status   = ?4,
    match_source   = ?5,
    match_attempts = match_attempts + 1,
    next_match_at  = CASE WHEN CAST(?6 AS TEXT) = '' THEN NULL
                          ELSE datetime('now', CAST(?6 AS TEXT)) END,
    updated_at     = CURRENT_TIMESTAMP
WHERE id = ?7 AND match_status <> 'manual'
`

type SaveNetflixTitleMatchParams struct {
	TmdbID      sql.NullString `json:"tmdb_id"`
	ImdbID      sql.NullString `json:"imdb_id"`
	TitleID     sql.NullInt64  `json:"title_id"`
	MatchStatus string         `json:"match_status"`
	MatchSource sql.NullString `json:"match_source"`
	RetryAfter  string         `json:"retry_after"`
	ID          int64          `json:"id"`
}

func (q *Queries) SaveNetflixTitleMatch(ctx context.Context, arg SaveNetflixTitleMatchParams) error {
	_, err := q.db.ExecContext(ctx, saveNetflixTitleMatch,
		arg.TmdbID,
		arg.ImdbID,
		arg.TitleID,
		arg.MatchStatus,
		arg.MatchSource,
		arg.RetryAfter,
		arg.ID,
	)
	return err
}

const upsertIMDbRating = `-- name: UpsertIMDbRating :exec
INSERT INTO imdb_ratings (imdb_id, average_rating, num_votes, imported_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(imdb_id) DO UPDATE SET
    average_rating = excluded.average_rating, num_votes = excluded.num_votes, imported_at = CURRENT_TIMESTAMP
`

type UpsertIMDbRatingParams struct {
	ImdbID        string  `json:"imdb_id"`
	AverageRating float64 `json:"average_rating"`
	NumVotes      int64   `json:"num_votes"`
}

func (q *Queries) UpsertIMDbRating(ctx context.Context, arg UpsertIMDbRatingParams) error {
	_, err := q.db.ExecContext(ctx, upsertIMDbRating, arg.ImdbID, arg.AverageRating, arg.NumVotes)
	return err
}

const upsertNetflixCountry = `-- name: UpsertNetflixCountry :exec
INSERT INTO netflix_top10_countries (country, week, category, weekly_rank, netflix_title_id, show_title, season_title, cumulative_weeks)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(country, week, category, weekly_rank) DO UPDATE SET
    netflix_title_id = excluded.netflix_title_id, show_title = excluded.show_title,
    season_title = excluded.season_title, cumulative_weeks = excluded.cumulative_weeks
`

type UpsertNetflixCountryParams struct {
	Country         string         `json:"country"`
	Week            string         `json:"week"`
	Category        string         `json:"category"`
	WeeklyRank      int64          `json:"weekly_rank"`
	NetflixTitleID  int64          `json:"netflix_title_id"`
	ShowTitle       string         `json:"show_title"`
	SeasonTitle     sql.NullString `json:"season_title"`
	CumulativeWeeks sql.NullInt64  `json:"cumulative_weeks"`
}

func (q *Queries) UpsertNetflixCountry(ctx context.Context, arg UpsertNetflixCountryParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetflixCountry,
		arg.Country,
		arg.Week,
		arg.Category,
		arg.WeeklyRank,
		arg.NetflixTitleID,
		arg.ShowTitle,
		arg.SeasonTitle,
		arg.CumulativeWeeks,
	)
	return err
}

const upsertNetflixGlobal = `-- name: UpsertNetflixGlobal :exec
INSERT INTO netflix_top10_global (week, category, weekly_rank, netflix_title_id, show_title, season_title,
    weekly_hours_viewed, runtime_hours, weekly_views, cumulative_weeks)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(week, category, weekly_rank) DO UPDATE SET
    netflix_title_id = excluded.netflix_title_id, show_title = excluded.show_title, season_title = excluded.season_title,
    weekly_hours_viewed = excluded.weekly_hours_viewed, runtime_hours = excluded.runtime_hours,
    weekly_views = excluded.weekly_views, cumulative_weeks = excluded.cumulative_weeks
`

type UpsertNetflixGlobalParams struct {
	Week              string          `json:"week"`
	Category          string          `json:"category"`
	WeeklyRank        int64           `json:"weekly_rank"`
	NetflixTitleID    int64           `json:"netflix_title_id"`
	ShowTitle         string          `json:"show_title"`
	SeasonTitle       sql.NullString  `json:"season_title"`
	WeeklyHoursViewed sql.NullInt64   `json:"weekly_hours_viewed"`
	RuntimeHours      sql.NullFloat64 `json:"runtime_hours"`
	WeeklyViews       sql.NullInt64   `json:"weekly_views"`
	CumulativeWeeks   sql.NullInt64   `json:"cumulative_weeks"`
}

func (q *Queries) UpsertNetflixGlobal(ctx context.Context, arg UpsertNetflixGlobalParams) error {
	_, err := q.db.ExecContext(ctx, upsertNetflixGlobal,
		arg.Week,
		arg.Category,
		arg.WeeklyRank,
		arg.NetflixTitleID,
		arg.ShowTitle,
		arg.SeasonTitle,
		arg.WeeklyHoursViewed,
		arg.RuntimeHours,
		arg.WeeklyViews,
		arg.CumulativeWeeks,
	)
	return err
}
