// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metadata.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"
)

const countTmdbTitles = `-- name: CountTmdbTitles :one
SELECT COUNT(*) AS titles,
       CAST(COALESCE(SUM(CASE WHEN details_fetched_at IS NOT NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS with_details,
       CAST(COALESCE(SUM(CASE WHEN wikidata_id IS NOT NULL THEN 1 ELSE 0 END), 0) AS INTEGER) AS with_wikidata
FROM tmdb_titles
`

type CountTmdbTitlesRow struct {
	Titles       int64 `json:"titles"`
	WithDetails  int64 `json:"with_details"`
	WithWikidata int64 `json:"with_wikidata"`
}

func (q *Queries) CountTmdbTitles(ctx context.Context) (CountTmdbTitlesRow, error) {
	row := q.db.QueryRowContext(ctx, countTmdbTitles)
	var i CountTmdbTitlesRow
	err := row.Scan(&i.Titles, &i.WithDetails, &i.WithWikidata)
	return i, err
}

const deleteTmdbWatchProviders = `-- name: DeleteTmdbWatchProviders :exec
DELETE FROM tmdb_watch_providers WHERE tmdb_kind = ? AND tmdb_id = ?
`

type DeleteTmdbWatchProvidersParams struct {
	TmdbKind string `json:"tmdb_kind"`
	TmdbID   string `json:"tmdb_id"`
}

func (q *Queries) DeleteTmdbWatchProviders(ctx context.Context, arg DeleteTmdbWatchProvidersParams) error {
	_, err := q.db.ExecContext(ctx, deleteTmdbWatchProviders, arg.TmdbKind, arg.TmdbID)
	return err
}

const getTmdbTitle = `-- name: GetTmdbTitle :one
SELECT tmdb_kind, tmdb_id, title, original_title, original_language, overview, status, release_date, last_air_date, runtime, number_of_seasons, number_of_episodes, genres, origin_countries, production_companies, networks, poster_path, backdrop_path, popularity, vote_average, vote_count, digital_release_dates, imdb_id, wikidata_id, rt_id, metacritic_id, letterboxd_id, details_fetched_at, wikidata_fetched_at, created_at, updated_at FROM tmdb_titles WHERE tmdb_kind = ? AND tmdb_id = ?
`

type GetTmdbTitleParams struct {
	TmdbKind string `json:"tmdb_kind"`
	TmdbID   string `json:"tmdb_id"`
}

func (q *Queries) GetTmdbTitle(ctx context.Context, arg GetTmdbTitleParams) (TmdbTitle, error) {
	row := q.db.QueryRowContext(ctx, getTmdbTitle, arg.TmdbKind, arg.TmdbID)
	var i TmdbTitle
	err := row.Scan(
		&i.TmdbKind,
		&i.TmdbID,
		&i.Title,
		&i.OriginalTitle,
		&i.OriginalLanguage,
		&i.Overview,
		&i.Status,
		&i.ReleaseDate,
		&i.LastAirDate,
		&i.Runtime,
		&i.NumberOfSeasons,
		&i.NumberOfEpisodes,
		&i.Genres,
		&i.OriginCountries,
		&i.ProductionCompanies,
		&i.Networks,
		&i.PosterPath,
		&i.BackdropPath,
		&i.Popularity,
		&i.VoteAverage,
		&i.VoteCount,
		&i.DigitalReleaseDates,
		&i.ImdbID,
		&i.WikidataID,
		&i.RtID,
		&i.MetacriticID,
		&i.LetterboxdID,
		&i.DetailsFetchedAt,
		&i.WikidataFetchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTmdbWatchProvider = `-- name: InsertTmdbWatchProvider :exec
INSERT INTO tmdb_watch_providers (tmdb_kind, tmdb_id, country, monetization, provider_id, provider_name, logo_path, display_priority, link)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tmdb_kind, tmdb_id, country, monetization, provider_id) DO NOTHING
`

type InsertTmdbWatchProviderParams struct {
	TmdbKind        string         `json:"tmdb_kind"`
	TmdbID          string         `json:"tmdb_id"`
	Country         string         `json:"country"`
	Monetization    string         `json:"monetization"`
	ProviderID      int64          `json:"provider_id"`
	ProviderName    string         `json:"provider_name"`
	LogoPath        sql.NullString `json:"logo_path"`
	DisplayPriority sql.NullInt64  `json:"display_priority"`
	Link            sql.NullString `json:"link"`
}

func (q *Queries) InsertTmdbWatchProvider(ctx context.Context, arg InsertTmdbWatchProviderParams) error {
	_, err := q.db.ExecContext(ctx, insertTmdbWatchProvider,
		arg.TmdbKind,
		arg.TmdbID,
		arg.Country,
		arg.Monetization,
		arg.ProviderID,
		arg.ProviderName,
		arg.LogoPath,
		arg.DisplayPriority,
		arg.Link,
	)
	return err
}

const listTmdbRefsDueForDetails = `-- name: ListTmdbRefsDueForDetails :many
SELECT k.tmdb_kind, k.tmdb_id
FROM (
    SELECT u.tmdb_kind, u.tmdb_id, MAX(u.last_seen) AS last_seen
    FROM (
        SELECT CASE t.kind WHEN 'tv_show' THEN 'tv' ELSE 'movie' END AS tmdb_kind, t.tmdb_id AS tmdb_id,
               (SELECT MAX(r.ranked_on) FROM rankings r WHERE r.title_id = t.id) AS last_seen
        FROM titles t
        WHERE COALESCE(t.tmdb_id, '') <> ''
        UNION ALL
        SELECT CASE n.kind WHEN 'tv_show' THEN 'tv' ELSE 'movie' END, n.tmdb_id,
               (SELECT MAX(g.week) FROM netflix_top10_global g WHERE g.netflix_title_id = n.id)
        FROM netflix_titles n
        WHERE COALESCE(n.tmdb_id, '') <> ''
    ) u
    GROUP BY u.tmdb_kind, u.tmdb_id
) k
LEFT JOIN tmdb_titles m ON m.tmdb_kind = k.tmdb_kind AND m.tmdb_id = k.tmdb_id
WHERE m.details_fetched_at IS NULL
   OR (k.last_seen >= date('now', '-30 days') AND m.details_fetched_at < datetime('now', CAST(?1 AS TEXT)))
   OR m.details_fetched_at < datetime('now', CAST(?2 AS TEXT))
ORDER BY m.details_fetched_at IS NOT NULL, k.last_seen DESC
LIMIT ?3
`

type ListTmdbRefsDueForDetailsParams struct {
	RecentWindow string `json:"recent_window"`
	StaleWindow  string `json:"stale_window"`
	Limit        int64  `json:"limit"`
}

type ListTmdbRefsDueForDetailsRow struct {
	TmdbKind string         `json:"tmdb_kind"`
	TmdbID   sql.NullString `json:"tmdb_id"`
}

// Matched TMDB titles (from FlixPatrol or Netflix titles) whose details are
// missing or older than the refresh window. Recently charting titles use the
// short window (watch providers change), the rest the long one.
// Windows are SQLite datetime modifiers, e.g. '-3 days' and '-30 days'.
func (q *Queries) ListTmdbRefsDueForDetails(ctx context.Context, arg ListTmdbRefsDueForDetailsParams) ([]ListTmdbRefsDueForDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTmdbRefsDueForDetails, arg.RecentWindow, arg.StaleWindow, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTmdbRefsDueForDetailsRow{}
	for rows.Next() {
		var i ListTmdbRefsDueForDetailsRow
		if err := rows.Scan(&i.TmdbKind, &i.TmdbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTmdbRefsDueForWikidata = `-- name: ListTmdbRefsDueForWikidata :many
SELECT k.tmdb_kind, k.tmdb_id
FROM (
    SELECT CASE kind WHEN 'tv_show' THEN 'tv' ELSE 'movie' END AS tmdb_kind, tmdb_id
    FROM titles WHERE COALESCE(tmdb_id, '') <> ''
    UNION
    SELECT CASE kind WHEN 'tv_show' THEN 'tv' ELSE 'movie' END, tmdb_id
    FROM netflix_titles WHERE COALESCE(tmdb_id, '') <> ''
) k
LEFT JOIN tmdb_titles m ON m.tmdb_kind = k.tmdb_kind AND m.tmdb_id = k.tmdb_id
WHERE m.wikidata_fetched_at IS NULL OR m.wikidata_fetched_at < datetime('now', CAST(?1 AS TEXT))
LIMIT ?2
`

type ListTmdbRefsDueForWikidataParams struct {
	Window string `json:"window"`
	Limit  int64  `json:"limit"`
}

type ListTmdbRefsDueForWikidataRow struct {
	TmdbKind string         `json:"tmdb_kind"`
	TmdbID   sql.NullString `json:"tmdb_id"`
}

// Matched TMDB titles never looked up on Wikidata, or not in the window.
func (q *Queries) ListTmdbRefsDueForWikidata(ctx context.Context, arg ListTmdbRefsDueForWikidataParams) ([]ListTmdbRefsDueForWikidataRow, error) {
	rows, err := q.db.QueryContext(ctx, listTmdbRefsDueForWikidata, arg.Window, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTmdbRefsDueForWikidataRow{}
	for rows.Next() {
		var i ListTmdbRefsDueForWikidataRow
		if err := rows.Scan(&i.TmdbKind, &i.TmdbID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTmdbTitlesByIDs = `-- name: ListTmdbTitlesByIDs :many
SELECT tmdb_kind, tmdb_id, title, original_title, original_language, overview, status, release_date, last_air_date, runtime, number_of_seasons, number_of_episodes, genres, origin_countries, production_companies, networks, poster_path, backdrop_path, popularity, vote_average, vote_count, digital_release_dates, imdb_id, wikidata_id, rt_id, metacritic_id, letterboxd_id, details_fetched_at, wikidata_fetched_at, created_at, updated_at FROM tmdb_titles WHERE tmdb_id IN (/*SLICE:ids*/?)
`

// Callers filter by kind (TMDB movie and TV IDs overlap).
func (q *Queries) ListTmdbTitlesByIDs(ctx context.Context, ids []string) ([]TmdbTitle, error) {
	query := listTmdbTitlesByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TmdbTitle{}
	for rows.Next() {
		var i TmdbTitle
		if err := rows.Scan(
			&i.TmdbKind,
			&i.TmdbID,
			&i.Title,
			&i.OriginalTitle,
			&i.OriginalLanguage,
			&i.Overview,
			&i.Status,
			&i.ReleaseDate,
			&i.LastAirDate,
			&i.Runtime,
			&i.NumberOfSeasons,
			&i.NumberOfEpisodes,
			&i.Genres,
			&i.OriginCountries,
			&i.ProductionCompanies,
			&i.Networks,
			&i.PosterPath,
			&i.BackdropPath,
			&i.Popularity,
			&i.VoteAverage,
			&i.VoteCount,
			&i.DigitalReleaseDates,
			&i.ImdbID,
			&i.WikidataID,
			&i.RtID,
			&i.MetacriticID,
			&i.LetterboxdID,
			&i.DetailsFetchedAt,
			&i.WikidataFetchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTmdbWatchProviders = `-- name: ListTmdbWatchProviders :many
SELECT tmdb_kind, tmdb_id, country, monetization, provider_id, provider_name, logo_path, display_priority, link, fetched_at FROM tmdb_watch_providers
WHERE tmdb_kind = ?1 AND tmdb_id = ?2
  AND (CAST(?3 AS TEXT) = '' OR country = ?3)
ORDER BY country, CASE monetization WHEN 'flatrate' THEN 0 WHEN 'free' THEN 1 WHEN 'ads' THEN 2 WHEN 'rent' THEN 3 ELSE 4 END,
         display_priority, provider_name
`

type ListTmdbWatchProvidersParams struct {
	TmdbKind string `json:"tmdb_kind"`
	TmdbID   string `json:"tmdb_id"`
	Country  string `json:"country"`
}

func (q *Queries) ListTmdbWatchProviders(ctx context.Context, arg ListTmdbWatchProvidersParams) ([]TmdbWatchProvider, error) {
	rows, err := q.db.QueryContext(ctx, listTmdbWatchProviders, arg.TmdbKind, arg.TmdbID, arg.Country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TmdbWatchProvider{}
	for rows.Next() {
		var i TmdbWatchProvider
		if err := rows.Scan(
			&i.TmdbKind,
			&i.TmdbID,
			&i.Country,
			&i.Monetization,
			&i.ProviderID,
			&i.ProviderName,
			&i.LogoPath,
			&i.DisplayPriority,
			&i.Link,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTmdbTitleDetails = `-- name: UpsertTmdbTitleDetails :exec

INSERT INTO tmdb_titles (
    tmdb_kind, tmdb_id, title, original_title, original_language, overview, status,
    release_date, last_air_date, runtime, number_of_seasons, number_of_episodes,
    genres, origin_countries, production_companies, networks, poster_path, backdrop_path,
    popularity, vote_average, vote_count, digital_release_dates, imdb_id, wikidata_id,
    details_fetched_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, ?7, ?8, ?9, ?10,
    ?11, ?12, ?13, ?14,
    ?15, ?16, ?17, ?18,
    ?19, ?20, ?21, ?22,
    ?23, ?24, CURRENT_TIMESTAMP
)
ON CONFLICT(tmdb_kind, tmdb_id) DO UPDATE SET
    title = excluded.title, original_title = excluded.original_title, original_language = excluded.original_language,
    overview = excluded.overview, status = excluded.status, release_date = excluded.release_date,
    last_air_date = excluded.last_air_date, runtime = excluded.runtime, number_of_seasons = excluded.number_of_seasons,
    number_of_episodes = excluded.number_of_episodes, genres = excluded.genres, origin_countries = excluded.origin_countries,
    production_companies = excluded.production_companies, networks = excluded.networks,
    poster_path = excluded.poster_path, backdrop_path = excluded.backdrop_path, popularity = excluded.popularity,
    vote_average = excluded.vote_average, vote_count = excluded.vote_count,
    digital_release_dates = excluded.digital_release_dates,
    imdb_id = COALESCE(excluded.imdb_id, tmdb_titles.imdb_id),
    wikidata_id = COALESCE(excluded.wikidata_id, tmdb_titles.wikidata_id),
    details_fetched_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
`

type UpsertTmdbTitleDetailsParams struct {
	TmdbKind            string          `json:"tmdb_kind"`
	TmdbID              string          `json:"tmdb_id"`
	Title               sql.NullString  `json:"title"`
	OriginalTitle       sql.NullString  `json:"original_title"`
	OriginalLanguage    sql.NullString  `json:"original_language"`
	Overview            sql.NullString  `json:"overview"`
	Status              sql.NullString  `json:"status"`
	ReleaseDate         sql.NullString  `json:"release_date"`
	LastAirDate         sql.NullString  `json:"last_air_date"`
	Runtime             sql.NullInt64   `json:"runtime"`
	NumberOfSeasons     sql.NullInt64   `json:"number_of_seasons"`
	NumberOfEpisodes    sql.NullInt64   `json:"number_of_episodes"`
	Genres              sql.NullString  `json:"genres"`
	OriginCountries     sql.NullString  `json:"origin_countries"`
	ProductionCompanies sql.NullString  `json:"production_companies"`
	Networks            sql.NullString  `json:"networks"`
	PosterPath          sql.NullString  `json:"poster_path"`
	BackdropPath        sql.NullString  `json:"backdrop_path"`
	Popularity          sql.NullFloat64 `json:"popularity"`
	VoteAverage         sql.NullFloat64 `json:"vote_average"`
	VoteCount           sql.NullInt64   `json:"vote_count"`
	DigitalReleaseDates sql.NullString  `json:"digital_release_dates"`
	ImdbID              sql.NullString  `json:"imdb_id"`
	WikidataID          sql.NullString  `json:"wikidata_id"`
}

// TMDB metadata, watch providers and Wikidata IDs per TMDB title.
func (q *Queries) UpsertTmdbTitleDetails(ctx context.Context, arg UpsertTmdbTitleDetailsParams) error {
	_, err := q.db.ExecContext(ctx, upsertTmdbTitleDetails,
		arg.TmdbKind,
		arg.TmdbID,
		arg.Title,
		arg.OriginalTitle,
		arg.OriginalLanguage,
		arg.Overview,
		arg.Status,
		arg.ReleaseDate,
		arg.LastAirDate,
		arg.Runtime,
		arg.NumberOfSeasons,
		arg.NumberOfEpisodes,
		arg.Genres,
		arg.OriginCountries,
		arg.ProductionCompanies,
		arg.Networks,
		arg.PosterPath,
		arg.BackdropPath,
		arg.Popularity,
		arg.VoteAverage,
		arg.VoteCount,
		arg.DigitalReleaseDates,
		arg.ImdbID,
		arg.WikidataID,
	)
	return err
}

const upsertTmdbTitleWikidata = `-- name: UpsertTmdbTitleWikidata :exec
INSERT INTO tmdb_titles (tmdb_kind, tmdb_id, imdb_id, wikidata_id, rt_id, metacritic_id, letterboxd_id, wikidata_fetched_at)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?7, CURRENT_TIMESTAMP)
ON CONFLICT(tmdb_kind, tmdb_id) DO UPDATE SET
    imdb_id = COALESCE(tmdb_titles.imdb_id, excluded.imdb_id),
    wikidata_id = COALESCE(excluded.wikidata_id, tmdb_titles.wikidata_id),
    rt_id = COALESCE(excluded.rt_id, tmdb_titles.rt_id),
    metacritic_id = COALESCE(excluded.metacritic_id, tmdb_titles.metacritic_id),
    letterboxd_id = COALESCE(excluded.letterboxd_id, tmdb_titles.letterboxd_id),
    wikidata_fetched_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
`

type UpsertTmdbTitleWikidataParams struct {
	TmdbKind     string         `json:"tmdb_kind"`
	TmdbID       string         `json:"tmdb_id"`
	ImdbID       sql.NullString `json:"imdb_id"`
	WikidataID   sql.NullString `json:"wikidata_id"`
	RtID         sql.NullString `json:"rt_id"`
	MetacriticID sql.NullString `json:"metacritic_id"`
	LetterboxdID sql.NullString `json:"letterboxd_id"`
}

func (q *Queries) UpsertTmdbTitleWikidata(ctx context.Context, arg UpsertTmdbTitleWikidataParams) error {
	_, err := q.db.ExecContext(ctx, upsertTmdbTitleWikidata,
		arg.TmdbKind,
		arg.TmdbID,
		arg.ImdbID,
		arg.WikidataID,
		arg.RtID,
		arg.MetacriticID,
		arg.LetterboxdID,
	)
	return err
}
