// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Ranking struct {
	ID                int64         `json:"id"`
	TitleID           int64         `json:"title_id"`
	RankedOn          time.Time     `json:"ranked_on"`
	Country           interface{}   `json:"country"`
	StreamingProvider string        `json:"streaming_provider"`
	Category          string        `json:"category"`
	Rank              int64         `json:"rank"`
	SeasonNumber      sql.NullInt64 `json:"season_number"`
	ScrapedAt         time.Time     `json:"scraped_at"`
}

type TaskRun struct {
	ID           int64          `json:"id"`
	ScheduleID   int64          `json:"schedule_id"`
	TaskType     string         `json:"task_type"`
	AsynqTaskID  sql.NullString `json:"asynq_task_id"`
	Status       string         `json:"status"`
	RetryCount   int64          `json:"retry_count"`
	MaxRetry     int64          `json:"max_retry"`
	StartedAt    time.Time      `json:"started_at"`
	FinishedAt   sql.NullTime   `json:"finished_at"`
	ErrorMessage sql.NullString `json:"error_message"`
}

type TaskRunLog struct {
	ID        int64     `json:"id"`
	RunID     int64     `json:"run_id"`
	Level     string    `json:"level"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

type TaskSchedule struct {
	ID                  int64     `json:"id"`
	TaskType            string    `json:"task_type"`
	Name                string    `json:"name"`
	Enabled             bool      `json:"enabled"`
	MaxRetries          int64     `json:"max_retries"`
	RequestDelaySeconds int64     `json:"request_delay_seconds"`
	RespectRobots       bool      `json:"respect_robots"`
	UserAgent           string    `json:"user_agent"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type TaskScheduleRunTime struct {
	ID         int64  `json:"id"`
	ScheduleID int64  `json:"schedule_id"`
	RunTimeUtc string `json:"run_time_utc"`
}

type TaskScheduleTarget struct {
	ID           int64  `json:"id"`
	ScheduleID   int64  `json:"schedule_id"`
	CountrySlug  string `json:"country_slug"`
	ProviderSlug string `json:"provider_slug"`
}

type Title struct {
	ID        int64          `json:"id"`
	Slug      string         `json:"slug"`
	Name      string         `json:"name"`
	Kind      string         `json:"kind"`
	TmdbID    sql.NullString `json:"tmdb_id"`
	ImdbID    sql.NullString `json:"imdb_id"`
	RtUrl     sql.NullString `json:"rt_url"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
