// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ops.sql

package sqlc

import (
	"context"
)

const getAppSetting = `-- name: GetAppSetting :one

SELECT value FROM app_settings WHERE key = ?
`

// Operations: settings lookups, chart freshness.
func (q *Queries) GetAppSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listLatestChartDates = `-- name: ListLatestChartDates :many
SELECT country, streaming_provider,
       CAST(MAX(ranked_on) AS TEXT) AS latest_date,
       CAST(MAX(scraped_at) AS TEXT) AS last_scraped_at
FROM chart_snapshots
GROUP BY country, streaming_provider
ORDER BY country, streaming_provider
`

type ListLatestChartDatesRow struct {
	Country           string `json:"country"`
	StreamingProvider string `json:"streaming_provider"`
	LatestDate        string `json:"latest_date"`
	LastScrapedAt     string `json:"last_scraped_at"`
}

// Latest stored date and scrape time of each country and provider chart.
func (q *Queries) ListLatestChartDates(ctx context.Context) ([]ListLatestChartDatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestChartDates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestChartDatesRow{}
	for rows.Next() {
		var i ListLatestChartDatesRow
		if err := rows.Scan(
			&i.Country,
			&i.StreamingProvider,
			&i.LatestDate,
			&i.LastScrapedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAppSetting = `-- name: SetAppSetting :exec
INSERT INTO app_settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
`

type SetAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetAppSetting(ctx context.Context, arg SetAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, setAppSetting, arg.Key, arg.Value)
	return err
}

const unmatchedTitlesByCountry = `-- name: UnmatchedTitlesByCountry :many
SELECT CAST(r.country AS TEXT) AS country, COUNT(DISTINCT t.id) AS titles
FROM rankings r
JOIN titles t ON t.id = r.title_id
WHERE t.match_status IN ('pending', 'unmatched')
  AND r.ranked_on >= CAST(?1 AS TEXT)
GROUP BY r.country
ORDER BY titles DESC
`

type UnmatchedTitlesByCountryRow struct {
	Country string `json:"country"`
	Titles  int64  `json:"titles"`
}

// Unmatched titles per country they charted in, from a date on.
func (q *Queries) UnmatchedTitlesByCountry(ctx context.Context, since string) ([]UnmatchedTitlesByCountryRow, error) {
	rows, err := q.db.QueryContext(ctx, unmatchedTitlesByCountry, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnmatchedTitlesByCountryRow{}
	for rows.Next() {
		var i UnmatchedTitlesByCountryRow
		if err := rows.Scan(&i.Country, &i.Titles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const weeklyMappingCoverage = `-- name: WeeklyMappingCoverage :many
SELECT strftime('%Y-%W', r.ranked_on) AS week,
       MIN(r.ranked_on) AS first_date,
       COUNT(*) AS entries,
       CAST(SUM(CASE WHEN COALESCE(t.tmdb_id, '') <> '' THEN 1 ELSE 0 END) AS INTEGER) AS mapped,
       CAST(SUM(CASE WHEN COALESCE(t.rt_url, '') <> '' THEN 1 ELSE 0 END) AS INTEGER) AS with_rt
FROM rankings r
JOIN titles t ON t.id = r.title_id
WHERE r.ranked_on >= CAST(?1 AS TEXT)
GROUP BY week
ORDER BY week
`

type WeeklyMappingCoverageRow struct {
	Week      interface{} `json:"week"`
	FirstDate interface{} `json:"first_date"`
	Entries   int64       `json:"entries"`
	Mapped    int64       `json:"mapped"`
	WithRt    int64       `json:"with_rt"`
}

// Share of chart entries whose title has a TMDB ID, per ISO week, from a date on.
func (q *Queries) WeeklyMappingCoverage(ctx context.Context, since string) ([]WeeklyMappingCoverageRow, error) {
	rows, err := q.db.QueryContext(ctx, weeklyMappingCoverage, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WeeklyMappingCoverageRow{}
	for rows.Next() {
		var i WeeklyMappingCoverageRow
		if err := rows.Scan(
			&i.Week,
			&i.FirstDate,
			&i.Entries,
			&i.Mapped,
			&i.WithRt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
