// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CompleteTaskRun(ctx context.Context, arg CompleteTaskRunParams) error
	CountTitles(ctx context.Context, arg CountTitlesParams) (int64, error)
	CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (TaskRun, error)
	CreateTaskRunLog(ctx context.Context, arg CreateTaskRunLogParams) error
	CreateTaskSchedule(ctx context.Context, arg CreateTaskScheduleParams) (TaskSchedule, error)
	CreateTaskScheduleRunTime(ctx context.Context, arg CreateTaskScheduleRunTimeParams) error
	CreateTaskScheduleTarget(ctx context.Context, arg CreateTaskScheduleTargetParams) error
	GetTaskRunByID(ctx context.Context, id int64) (TaskRun, error)
	GetTaskScheduleByID(ctx context.Context, id int64) (TaskSchedule, error)
	GetTitleByID(ctx context.Context, id int64) (Title, error)
	GetTitleBySlug(ctx context.Context, slug string) (Title, error)
	ListEnabledTaskSchedules(ctx context.Context) ([]TaskSchedule, error)
	ListTitles(ctx context.Context, arg ListTitlesParams) ([]Title, error)
	ListTaskRunLogsByRunID(ctx context.Context, runID int64) ([]TaskRunLog, error)
	ListTaskRuns(ctx context.Context, arg ListTaskRunsParams) ([]TaskRun, error)
	ListTaskRunsByScheduleID(ctx context.Context, arg ListTaskRunsByScheduleIDParams) ([]TaskRun, error)
	ListTaskScheduleRunTimesByScheduleID(ctx context.Context, scheduleID int64) ([]TaskScheduleRunTime, error)
	ListTaskScheduleTargetsByScheduleID(ctx context.Context, scheduleID int64) ([]TaskScheduleTarget, error)
	ListTaskSchedules(ctx context.Context, arg ListTaskSchedulesParams) ([]TaskSchedule, error)
	ListTop10AllProviders(ctx context.Context, arg ListTop10AllProvidersParams) ([]ListTop10AllProvidersRow, error)
	ListTop10ByProvider(ctx context.Context, arg ListTop10ByProviderParams) ([]ListTop10ByProviderRow, error)
	DeleteTaskScheduleRunTimesByScheduleID(ctx context.Context, scheduleID int64) error
	UpdateTaskSchedule(ctx context.Context, arg UpdateTaskScheduleParams) (TaskSchedule, error)
	UpdateTitleIDs(ctx context.Context, arg UpdateTitleIDsParams) (Title, error)
	UpsertRanking(ctx context.Context, arg UpsertRankingParams) (Ranking, error)
	// Titles (movies + tv shows) + daily rankings (Top 10).
	UpsertTitle(ctx context.Context, arg UpsertTitleParams) (Title, error)
}

var _ Querier = (*Queries)(nil)
