// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const deleteTitleRatingSourcesByProvider = `-- name: DeleteTitleRatingSourcesByProvider :exec
DELETE FROM title_rating_sources
WHERE tmdb_kind = ? AND tmdb_id = ? AND provider = ?
`

type DeleteTitleRatingSourcesByProviderParams struct {
	TmdbKind string `json:"tmdb_kind"`
	TmdbID   string `json:"tmdb_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteTitleRatingSourcesByProvider(ctx context.Context, arg DeleteTitleRatingSourcesByProviderParams) error {
	_, err := q.db.ExecContext(ctx, deleteTitleRatingSourcesByProvider, arg.TmdbKind, arg.TmdbID, arg.Provider)
	return err
}

const fillTitleExternalIDs = `-- name: FillTitleExternalIDs :exec
UPDATE titles
SET
    imdb_id    = COALESCE(imdb_id, ?1),
    rt_url     = COALESCE(rt_url, ?2),
    updated_at = CURRENT_TIMESTAMP
WHERE tmdb_id = ?3
  AND kind = ?4
  AND ((imdb_id IS NULL AND ?1 IS NOT NULL)
    OR (rt_url IS NULL AND ?2 IS NOT NULL))
`

type FillTitleExternalIDsParams struct {
	ImdbID sql.NullString `json:"imdb_id"`
	RtUrl  sql.NullString `json:"rt_url"`
	TmdbID sql.NullString `json:"tmdb_id"`
	Kind   string         `json:"kind"`
}

// Back-fill IDs found while rating onto scraped titles that lack them.
func (q *Queries) FillTitleExternalIDs(ctx context.Context, arg FillTitleExternalIDsParams) error {
	_, err := q.db.ExecContext(ctx, fillTitleExternalIDs,
		arg.ImdbID,
		arg.RtUrl,
		arg.TmdbID,
		arg.Kind,
	)
	return err
}

const getTitleRatings = `-- name: GetTitleRatings :one

SELECT id, tmdb_kind, tmdb_id, title, year, imdb_id, justwatch_id, rt_slug, refreshed_at, created_at, updated_at
FROM title_ratings
WHERE tmdb_kind = ? AND tmdb_id = ?
`

type GetTitleRatingsParams struct {
	TmdbKind string `json:"tmdb_kind"`
	TmdbID   string `json:"tmdb_id"`
}

// On-demand ratings cache, keyed by TMDB namespace ('movie' | 'tv') + ID.
func (q *Queries) GetTitleRatings(ctx context.Context, arg GetTitleRatingsParams) (TitleRating, error) {
	row := q.db.QueryRowContext(ctx, getTitleRatings, arg.TmdbKind, arg.TmdbID)
	var i TitleRating
	err := row.Scan(
		&i.ID,
		&i.TmdbKind,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.JustwatchID,
		&i.RtSlug,
		&i.RefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTitleRatingSource = `-- name: InsertTitleRatingSource :exec
INSERT INTO title_rating_sources (tmdb_kind, tmdb_id, provider, source, value, votes, url, fetched_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTitleRatingSourceParams struct {
	TmdbKind  string         `json:"tmdb_kind"`
	TmdbID    string         `json:"tmdb_id"`
	Provider  string         `json:"provider"`
	Source    string         `json:"source"`
	Value     float64        `json:"value"`
	Votes     sql.NullInt64  `json:"votes"`
	Url       sql.NullString `json:"url"`
	FetchedAt time.Time      `json:"fetched_at"`
}

func (q *Queries) InsertTitleRatingSource(ctx context.Context, arg InsertTitleRatingSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertTitleRatingSource,
		arg.TmdbKind,
		arg.TmdbID,
		arg.Provider,
		arg.Source,
		arg.Value,
		arg.Votes,
		arg.Url,
		arg.FetchedAt,
	)
	return err
}

const listTitleRatingSources = `-- name: ListTitleRatingSources :many
SELECT provider, source, value, votes, url, fetched_at
FROM title_rating_sources
WHERE tmdb_kind = ? AND tmdb_id = ?
ORDER BY provider, source
`

type ListTitleRatingSourcesParams struct {
	TmdbKind string `json:"tmdb_kind"`
	TmdbID   string `json:"tmdb_id"`
}

type ListTitleRatingSourcesRow struct {
	Provider  string         `json:"provider"`
	Source    string         `json:"source"`
	Value     float64        `json:"value"`
	Votes     sql.NullInt64  `json:"votes"`
	Url       sql.NullString `json:"url"`
	FetchedAt time.Time      `json:"fetched_at"`
}

func (q *Queries) ListTitleRatingSources(ctx context.Context, arg ListTitleRatingSourcesParams) ([]ListTitleRatingSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTitleRatingSources, arg.TmdbKind, arg.TmdbID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTitleRatingSourcesRow{}
	for rows.Next() {
		var i ListTitleRatingSourcesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Source,
			&i.Value,
			&i.Votes,
			&i.Url,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTitleRatings = `-- name: UpsertTitleRatings :one
INSERT INTO title_ratings (tmdb_kind, tmdb_id, title, year, imdb_id, justwatch_id, rt_slug, refreshed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(tmdb_kind, tmdb_id) DO UPDATE SET
    title        = excluded.title,
    year         = excluded.year,
    imdb_id      = excluded.imdb_id,
    justwatch_id = excluded.justwatch_id,
    rt_slug      = excluded.rt_slug,
    refreshed_at = excluded.refreshed_at,
    updated_at   = CURRENT_TIMESTAMP
RETURNING id, tmdb_kind, tmdb_id, title, year, imdb_id, justwatch_id, rt_slug, refreshed_at, created_at, updated_at
`

type UpsertTitleRatingsParams struct {
	TmdbKind    string         `json:"tmdb_kind"`
	TmdbID      string         `json:"tmdb_id"`
	Title       sql.NullString `json:"title"`
	Year        sql.NullInt64  `json:"year"`
	ImdbID      sql.NullString `json:"imdb_id"`
	JustwatchID sql.NullString `json:"justwatch_id"`
	RtSlug      sql.NullString `json:"rt_slug"`
	RefreshedAt time.Time      `json:"refreshed_at"`
}

func (q *Queries) UpsertTitleRatings(ctx context.Context, arg UpsertTitleRatingsParams) (TitleRating, error) {
	row := q.db.QueryRowContext(ctx, upsertTitleRatings,
		arg.TmdbKind,
		arg.TmdbID,
		arg.Title,
		arg.Year,
		arg.ImdbID,
		arg.JustwatchID,
		arg.RtSlug,
		arg.RefreshedAt,
	)
	var i TitleRating
	err := row.Scan(
		&i.ID,
		&i.TmdbKind,
		&i.TmdbID,
		&i.Title,
		&i.Year,
		&i.ImdbID,
		&i.JustwatchID,
		&i.RtSlug,
		&i.RefreshedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
