// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_runs.sql

package sqlc

import (
	"context"
	"database/sql"
)

const completeTaskRun = `-- name: CompleteTaskRun :exec
UPDATE task_runs
SET status = ?, finished_at = CURRENT_TIMESTAMP, error_message = ?
WHERE id = ?
`

type CompleteTaskRunParams struct {
	Status       string         `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           int64          `json:"id"`
}

func (q *Queries) CompleteTaskRun(ctx context.Context, arg CompleteTaskRunParams) error {
	_, err := q.db.ExecContext(ctx, completeTaskRun, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}

const createTaskRun = `-- name: CreateTaskRun :one
INSERT INTO task_runs (schedule_id, task_type, asynq_task_id, status, retry_count, max_retry)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, schedule_id, task_type, asynq_task_id, status, retry_count, max_retry, started_at, finished_at, error_message
`

type CreateTaskRunParams struct {
	ScheduleID  int64          `json:"schedule_id"`
	TaskType    string         `json:"task_type"`
	AsynqTaskID sql.NullString `json:"asynq_task_id"`
	Status      string         `json:"status"`
	RetryCount  int64          `json:"retry_count"`
	MaxRetry    int64          `json:"max_retry"`
}

func (q *Queries) CreateTaskRun(ctx context.Context, arg CreateTaskRunParams) (TaskRun, error) {
	row := q.db.QueryRowContext(ctx, createTaskRun,
		arg.ScheduleID,
		arg.TaskType,
		arg.AsynqTaskID,
		arg.Status,
		arg.RetryCount,
		arg.MaxRetry,
	)
	var i TaskRun
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.TaskType,
		&i.AsynqTaskID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetry,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const createTaskRunLog = `-- name: CreateTaskRunLog :exec
INSERT INTO task_run_logs (run_id, level, message)
VALUES (?, ?, ?)
`

type CreateTaskRunLogParams struct {
	RunID   int64  `json:"run_id"`
	Level   string `json:"level"`
	Message string `json:"message"`
}

func (q *Queries) CreateTaskRunLog(ctx context.Context, arg CreateTaskRunLogParams) error {
	_, err := q.db.ExecContext(ctx, createTaskRunLog, arg.RunID, arg.Level, arg.Message)
	return err
}

const getTaskRunByID = `-- name: GetTaskRunByID :one
SELECT id, schedule_id, task_type, asynq_task_id, status, retry_count, max_retry, started_at, finished_at, error_message
FROM task_runs
WHERE id = ?
`

func (q *Queries) GetTaskRunByID(ctx context.Context, id int64) (TaskRun, error) {
	row := q.db.QueryRowContext(ctx, getTaskRunByID, id)
	var i TaskRun
	err := row.Scan(
		&i.ID,
		&i.ScheduleID,
		&i.TaskType,
		&i.AsynqTaskID,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetry,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const listTaskRunLogsByRunID = `-- name: ListTaskRunLogsByRunID :many
SELECT id, run_id, level, message, created_at
FROM task_run_logs
WHERE run_id = ?
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListTaskRunLogsByRunID(ctx context.Context, runID int64) ([]TaskRunLog, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRunLogsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskRunLog{}
	for rows.Next() {
		var i TaskRunLog
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Level,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRuns = `-- name: ListTaskRuns :many
SELECT id, schedule_id, task_type, asynq_task_id, status, retry_count, max_retry, started_at, finished_at, error_message
FROM task_runs
WHERE (? = 0 OR task_type = ?)
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListTaskRunsParams struct {
	Column1  interface{} `json:"column_1"`
	TaskType string      `json:"task_type"`
	Limit    int64       `json:"limit"`
	Offset   int64       `json:"offset"`
}

func (q *Queries) ListTaskRuns(ctx context.Context, arg ListTaskRunsParams) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRuns,
		arg.Column1,
		arg.TaskType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskRun{}
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.TaskType,
			&i.AsynqTaskID,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetry,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRunsByScheduleID = `-- name: ListTaskRunsByScheduleID :many
SELECT id, schedule_id, task_type, asynq_task_id, status, retry_count, max_retry, started_at, finished_at, error_message
FROM task_runs
WHERE schedule_id = ?
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListTaskRunsByScheduleIDParams struct {
	ScheduleID int64 `json:"schedule_id"`
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
}

func (q *Queries) ListTaskRunsByScheduleID(ctx context.Context, arg ListTaskRunsByScheduleIDParams) ([]TaskRun, error) {
	rows, err := q.db.QueryContext(ctx, listTaskRunsByScheduleID, arg.ScheduleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskRun{}
	for rows.Next() {
		var i TaskRun
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.TaskType,
			&i.AsynqTaskID,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetry,
			&i.StartedAt,
			&i.FinishedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
