// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_schedules.sql

package sqlc

import (
	"context"
)

const createTaskSchedule = `-- name: CreateTaskSchedule :one
INSERT INTO task_schedules (task_type, name, enabled, max_retries, request_delay_seconds, respect_robots, user_agent)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, task_type, name, enabled, max_retries, request_delay_seconds, respect_robots, user_agent, created_at, updated_at
`

type CreateTaskScheduleParams struct {
	TaskType            string `json:"task_type"`
	Name                string `json:"name"`
	Enabled             bool   `json:"enabled"`
	MaxRetries          int64  `json:"max_retries"`
	RequestDelaySeconds int64  `json:"request_delay_seconds"`
	RespectRobots       bool   `json:"respect_robots"`
	UserAgent           string `json:"user_agent"`
}

func (q *Queries) CreateTaskSchedule(ctx context.Context, arg CreateTaskScheduleParams) (TaskSchedule, error) {
	row := q.db.QueryRowContext(ctx, createTaskSchedule,
		arg.TaskType,
		arg.Name,
		arg.Enabled,
		arg.MaxRetries,
		arg.RequestDelaySeconds,
		arg.RespectRobots,
		arg.UserAgent,
	)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Name,
		&i.Enabled,
		&i.MaxRetries,
		&i.RequestDelaySeconds,
		&i.RespectRobots,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskScheduleRunTimesByScheduleID = `-- name: DeleteTaskScheduleRunTimesByScheduleID :exec
DELETE FROM task_schedule_run_times WHERE schedule_id = ?
`

func (q *Queries) DeleteTaskScheduleRunTimesByScheduleID(ctx context.Context, scheduleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTaskScheduleRunTimesByScheduleID, scheduleID)
	return err
}

const updateTaskSchedule = `-- name: UpdateTaskSchedule :one
UPDATE task_schedules
SET name = ?, enabled = ?, max_retries = ?,
    request_delay_seconds = ?, respect_robots = ?, user_agent = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, task_type, name, enabled, max_retries, request_delay_seconds, respect_robots, user_agent, created_at, updated_at
`

type UpdateTaskScheduleParams struct {
	Name                string `json:"name"`
	Enabled             bool   `json:"enabled"`
	MaxRetries          int64  `json:"max_retries"`
	RequestDelaySeconds int64  `json:"request_delay_seconds"`
	RespectRobots       bool   `json:"respect_robots"`
	UserAgent           string `json:"user_agent"`
	ID                  int64  `json:"id"`
}

func (q *Queries) UpdateTaskSchedule(ctx context.Context, arg UpdateTaskScheduleParams) (TaskSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateTaskSchedule,
		arg.Name,
		arg.Enabled,
		arg.MaxRetries,
		arg.RequestDelaySeconds,
		arg.RespectRobots,
		arg.UserAgent,
		arg.ID,
	)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Name,
		&i.Enabled,
		&i.MaxRetries,
		&i.RequestDelaySeconds,
		&i.RespectRobots,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskScheduleRunTime = `-- name: CreateTaskScheduleRunTime :exec
INSERT INTO task_schedule_run_times (schedule_id, run_time_utc)
VALUES (?, ?)
ON CONFLICT(schedule_id, run_time_utc) DO NOTHING
`

type CreateTaskScheduleRunTimeParams struct {
	ScheduleID int64  `json:"schedule_id"`
	RunTimeUtc string `json:"run_time_utc"`
}

func (q *Queries) CreateTaskScheduleRunTime(ctx context.Context, arg CreateTaskScheduleRunTimeParams) error {
	_, err := q.db.ExecContext(ctx, createTaskScheduleRunTime, arg.ScheduleID, arg.RunTimeUtc)
	return err
}

const createTaskScheduleTarget = `-- name: CreateTaskScheduleTarget :exec
INSERT INTO task_schedule_targets (schedule_id, country_slug, provider_slug)
VALUES (?, ?, ?)
ON CONFLICT(schedule_id, country_slug, provider_slug) DO NOTHING
`

type CreateTaskScheduleTargetParams struct {
	ScheduleID   int64  `json:"schedule_id"`
	CountrySlug  string `json:"country_slug"`
	ProviderSlug string `json:"provider_slug"`
}

func (q *Queries) CreateTaskScheduleTarget(ctx context.Context, arg CreateTaskScheduleTargetParams) error {
	_, err := q.db.ExecContext(ctx, createTaskScheduleTarget, arg.ScheduleID, arg.CountrySlug, arg.ProviderSlug)
	return err
}

const getTaskScheduleByID = `-- name: GetTaskScheduleByID :one
SELECT id, task_type, name, enabled, max_retries, request_delay_seconds, respect_robots, user_agent, created_at, updated_at
FROM task_schedules
WHERE id = ?
`

func (q *Queries) GetTaskScheduleByID(ctx context.Context, id int64) (TaskSchedule, error) {
	row := q.db.QueryRowContext(ctx, getTaskScheduleByID, id)
	var i TaskSchedule
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Name,
		&i.Enabled,
		&i.MaxRetries,
		&i.RequestDelaySeconds,
		&i.RespectRobots,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledTaskSchedules = `-- name: ListEnabledTaskSchedules :many
SELECT id, task_type, name, enabled, max_retries, request_delay_seconds, respect_robots, user_agent, created_at, updated_at
FROM task_schedules
WHERE enabled = 1
ORDER BY id ASC
`

func (q *Queries) ListEnabledTaskSchedules(ctx context.Context) ([]TaskSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledTaskSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskSchedule{}
	for rows.Next() {
		var i TaskSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Name,
			&i.Enabled,
			&i.MaxRetries,
			&i.RequestDelaySeconds,
			&i.RespectRobots,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskScheduleRunTimesByScheduleID = `-- name: ListTaskScheduleRunTimesByScheduleID :many
SELECT id, schedule_id, run_time_utc
FROM task_schedule_run_times
WHERE schedule_id = ?
ORDER BY run_time_utc ASC
`

func (q *Queries) ListTaskScheduleRunTimesByScheduleID(ctx context.Context, scheduleID int64) ([]TaskScheduleRunTime, error) {
	rows, err := q.db.QueryContext(ctx, listTaskScheduleRunTimesByScheduleID, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskScheduleRunTime{}
	for rows.Next() {
		var i TaskScheduleRunTime
		if err := rows.Scan(&i.ID, &i.ScheduleID, &i.RunTimeUtc); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskScheduleTargetsByScheduleID = `-- name: ListTaskScheduleTargetsByScheduleID :many
SELECT id, schedule_id, country_slug, provider_slug
FROM task_schedule_targets
WHERE schedule_id = ?
ORDER BY id ASC
`

func (q *Queries) ListTaskScheduleTargetsByScheduleID(ctx context.Context, scheduleID int64) ([]TaskScheduleTarget, error) {
	rows, err := q.db.QueryContext(ctx, listTaskScheduleTargetsByScheduleID, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskScheduleTarget{}
	for rows.Next() {
		var i TaskScheduleTarget
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleID,
			&i.CountrySlug,
			&i.ProviderSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskSchedules = `-- name: ListTaskSchedules :many
SELECT id, task_type, name, enabled, max_retries, request_delay_seconds, respect_robots, user_agent, created_at, updated_at
FROM task_schedules
WHERE (? = 0 OR enabled = ?)
  AND (? = 0 OR task_type = ?)
ORDER BY id ASC
`

type ListTaskSchedulesParams struct {
	Column1  interface{} `json:"column_1"`
	Enabled  bool        `json:"enabled"`
	Column3  interface{} `json:"column_3"`
	TaskType string      `json:"task_type"`
}

func (q *Queries) ListTaskSchedules(ctx context.Context, arg ListTaskSchedulesParams) ([]TaskSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listTaskSchedules,
		arg.Column1,
		arg.Enabled,
		arg.Column3,
		arg.TaskType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskSchedule{}
	for rows.Next() {
		var i TaskSchedule
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Name,
			&i.Enabled,
			&i.MaxRetries,
			&i.RequestDelaySeconds,
			&i.RespectRobots,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
