// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: top10_read.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const listTop10AllProviders = `-- name: ListTop10AllProviders :many
SELECT
    r.ranked_on,
    r.country,
    r.streaming_provider,
    r.category,
    r.rank,
    t.slug,
    t.name,
    t.kind,
    t.tmdb_id,
    t.imdb_id,
    t.rt_url
FROM rankings r
JOIN titles t ON t.id = r.title_id
WHERE r.ranked_on = ?
  AND r.country = ?
  AND r.category = ?
ORDER BY r.streaming_provider ASC, r.rank ASC
`

type ListTop10AllProvidersParams struct {
	RankedOn time.Time   `json:"ranked_on"`
	Country  interface{} `json:"country"`
	Category string      `json:"category"`
}

type ListTop10AllProvidersRow struct {
	RankedOn          time.Time      `json:"ranked_on"`
	Country           interface{}    `json:"country"`
	StreamingProvider string         `json:"streaming_provider"`
	Category          string         `json:"category"`
	Rank              int64          `json:"rank"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	Kind              string         `json:"kind"`
	TmdbID            sql.NullString `json:"tmdb_id"`
	ImdbID            sql.NullString `json:"imdb_id"`
	RtUrl             sql.NullString `json:"rt_url"`
}

func (q *Queries) ListTop10AllProviders(ctx context.Context, arg ListTop10AllProvidersParams) ([]ListTop10AllProvidersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTop10AllProviders, arg.RankedOn, arg.Country, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTop10AllProvidersRow{}
	for rows.Next() {
		var i ListTop10AllProvidersRow
		if err := rows.Scan(
			&i.RankedOn,
			&i.Country,
			&i.StreamingProvider,
			&i.Category,
			&i.Rank,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.TmdbID,
			&i.ImdbID,
			&i.RtUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTop10ByProvider = `-- name: ListTop10ByProvider :many
SELECT
    r.ranked_on,
    r.country,
    r.streaming_provider,
    r.category,
    r.rank,
    t.slug,
    t.name,
    t.kind,
    t.tmdb_id,
    t.imdb_id,
    t.rt_url
FROM rankings r
JOIN titles t ON t.id = r.title_id
WHERE r.ranked_on = ?
  AND r.country = ?
  AND r.streaming_provider = ?
  AND r.category = ?
ORDER BY r.rank ASC
`

type ListTop10ByProviderParams struct {
	RankedOn          time.Time   `json:"ranked_on"`
	Country           interface{} `json:"country"`
	StreamingProvider string      `json:"streaming_provider"`
	Category          string      `json:"category"`
}

type ListTop10ByProviderRow struct {
	RankedOn          time.Time      `json:"ranked_on"`
	Country           interface{}    `json:"country"`
	StreamingProvider string         `json:"streaming_provider"`
	Category          string         `json:"category"`
	Rank              int64          `json:"rank"`
	Slug              string         `json:"slug"`
	Name              string         `json:"name"`
	Kind              string         `json:"kind"`
	TmdbID            sql.NullString `json:"tmdb_id"`
	ImdbID            sql.NullString `json:"imdb_id"`
	RtUrl             sql.NullString `json:"rt_url"`
}

func (q *Queries) ListTop10ByProvider(ctx context.Context, arg ListTop10ByProviderParams) ([]ListTop10ByProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, listTop10ByProvider,
		arg.RankedOn,
		arg.Country,
		arg.StreamingProvider,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTop10ByProviderRow{}
	for rows.Next() {
		var i ListTop10ByProviderRow
		if err := rows.Scan(
			&i.RankedOn,
			&i.Country,
			&i.StreamingProvider,
			&i.Category,
			&i.Rank,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.TmdbID,
			&i.ImdbID,
			&i.RtUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
